version: "3.9"

services:
  fixed_point_app:
    build: .
    container_name: fixed_point_app
    command: ["python", "-m", "app.cli"]
    volumes:
      - ./app/app_logs.db:/app/app/app_logs.db
    environment:
      - PYTHONUNBUFFERED=1


